---
title: "Statistical Computing in R"
tbl-colwidths: [5,15,45,45,30,15,15]
---

This page contains an outline of the topics, content, and assignments for the quarter. Note that this schedule will be updated as the quarter progresses, with all changes documented here.

| Week | Day          | Topic / Reading                                                                                                         | Slides                                                                         | Starter Notes                                 | Practice Activity                   | Lab                                   |
|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
| 1    | Tue, 4/1     | [1: Introduction](https://manncz.github.io/stat331-calpoly-text/01-introduction.html)                                   | [Syllabus & Intro to R](slides/week-1/w1-intro-r.qmd)                          | [Week 1](student-versions/notes/w1-notes.qmd) | [PA 1](practice-activities/pa1.qmd) |                                       |
|      | Thu, 4/3     |                                                                                                                         | [Intro to Quarto](slides/week-1/w1-notebooks.qmd)                              |                                               |                                     | [Lab 1](labs/lab1/lab1-quarto.qmd)    |
| 2    | Tue, 4/8     | [2: Basics of Graphics](https://manncz.github.io/stat331-calpoly-text/02-tidy-data-and-basics-of-graphics.html)         | [Importing Data + Graphics with `ggplot2`](slides/week-2/w2-import-ggplot.qmd) | [Week 2](student-versions/notes/w2-notes.qmd) | [PA 2](practice-activities/pa2.qmd) |                                       |
|      | Thu, 4/10    |                                                                                                                         | [More Graphics!](slides/week-2/w2-graphics.qmd)                                |                                               |                                     | [Lab 2](labs/lab2/lab2-ggplot.qmd)    |
| 3    | Tue, 4/15    | [3: Data Cleaning + Manipulation](https://manncz.github.io/stat331-calpoly-text/03-data-cleaning-and-manipulation.html) | [Data Cleaning with](slides/week-3/w3-dplyr.qmd) `dplyr`                       | [Week 3](student-versions/notes/w3-notes.qmd) | [PA 3](practice-activities/pa3.qmd) |                                       |
|      | Thu, 4/17    | [Data Feminism: The Numbers Don't Speak for Themselves](https://data-feminism.mitpress.mit.edu/pub/czq9dfs5/release/3)  | [Extending `dplyr` + Data Ethics](slides/week-3/w3-more-dplyr-ethics.qmd)      |                                               |                                     | [Lab 3](labs/lab3/lab3-dplyr.qmd)     |
| 4    | Tue, 4/22    | [4: Data Joins + Transformations](https://manncz.github.io/stat331-calpoly-text/04-data-joins-and-transformations.html) | [Data Joins + Pivots](slides/week-4/w4-joins-pivots.qmd)                       |                                               | [PA 4](practice-activities/pa4.qmd) |                                       |
|      | Thu, 4/24    |                                                                                                                         | [Factor Variables](slides/week-4/w4-factors.qmd)                               |                                               |                                     | [Lab 4](labs/lab4/lab4-childcare.qmd) |
| 5    | Tue, 4/29    | [5: Special Data Types](5%20Special%20Data%20Types)                                                                     | Strings                                                                        |                                               |                                     |                                       |
|      | Thu, 5/1     |                                                                                                                         | Dates + TBD                                                                    |                                               |                                     |                                       |
| 6    | Tue, 5/6     | [6: Version Control](6%20Version%20Control)                                                                             | Version Control                                                                |                                               |                                     |                                       |
|      | **Thu, 5/8** |                                                                                                                         | **Midterm Exam**                                                               |                                               |                                     |                                       |
