---
title: "Midterm Exam"
format: 
  revealjs:
    theme: [default, ../slide_custom.scss]
editor: source
---

```{r setup}
#| include: false
#| message: false
library(tidyverse)
```

## Thursday, May 8 -- Midterm Exam

+ Right now, the only thing on your desk should be something to write with.

+ I will pass out a hard copy of the exam.

+ Do not look past the first page until I say you can start.

+ Canvas will unlock the **.qmd** template at the beginning of class.


You are great!! 



## Thursday, May 8 -- Midterm Exam

**Section 1: General Questions**

+ Cannot work on Section 2 until hand Section 1 to me.

**Section 2: Short Answer**

+ Now you can use anything you want except other people and AI.
+ **Download the `.qmd` template from Canvas.**
+ Submit `.qmd` and `.html` files on Canvas by the end of class.
+ Return the question sheet to me ehrn you finish.

**Section 3: Open-Ended Analysis -- After Class**

## To do...

+ Read **Chapter 7: Writing Functions**
  + Check-in 7.1 due Tuesday, 5/13 before class

+ **Final Project Group Contract**
  + I assigned groups and posted them on Canvas
  + Find some time to meet or coordinate with your assigned group to work on this next week
  + Due *next* Friday, 5/16 at 11:59pm

  

  